# https://wiki.hyprland.org/Configuring/

################
### MONITORS ###
################
# See https://wiki.hyprland.org/Configuring/Monitors/
monitor = eDP-1,preferred,auto,1
#monitor = eDP-1,disable
monitor = HDMI-A-1,preferred,auto,1


###################
### MY PROGRAMS ###
###################
# See https://wiki.hyprland.org/Configuring/Keywords/
$terminal = alacritty
$fileManager = dolphin
$menu = rofi -show drun


#################
### AUTOSTART ###
#################
exec-once = swww init
exec-once = ~/bin/pywaltic
exec-once = systemctl --user start hyprpolkitagent
exec-once = nm-applet


#############################
### ENVIRONMENT VARIABLES ###
#############################
# See https://wiki.hyprland.org/Configuring/Environment-variables/
env = XCURSOR_SIZE,22
env = HYPRCURSOR_SIZE,22

#env = QT_QPA_PLATFORM,wayland
#env = QT_STYLE_OVERRIDE,kvantum
#env = QT_QPA_PLATFORMTHEME,qt5ct

env = QT_QPA_PLATFORMTHEME,kde
env = QT_QPA_PLATFORM,wayland
env = XDG_MENU_PREFIX,plasma-


##########################
### OTHER CONFIG FILES ###
##########################
source = ~/.config/hypr/keybindings.conf
source = ~/.config/hypr/winWork.conf
source = ~/.config/hypr/input.conf
source = ~/.config/hypr/lookFeel.conf
