-- Generated by HyprMod

-- Settings
hl.config({
    decoration = {
        blur = {
            brightness = 1.15,
            contrast = 1.0,
            noise = 0.015,
            popups = true,
            size = 4,
            vibrancy = 0.3,
        },
        inactive_opacity = 0.8,
        rounding = 5,
        rounding_power = 8.0,
    },
})
