###################
### KEYBINDINGS ###
###################
# See https://wiki.hyprland.org/Configuring/Keywords/
$mainMod = SUPER # Sets "Windows" key as main modifier

# Spawn Terminal
bind = $mainMod, RETURN, exec, $terminal

# Kill Janela
bind = $mainMod SHIFT, Q, killactive,

# Sair do Hyprland
bind = $mainMod, M, exit,

# Abrir config
bind = $mainMod SHIFT, C, exec, alacritty --working-directory ~/.config/hypr -e nvim hyprland.conf

# Spawn Filemanager
bind = $mainMod SHIFT, A, exec, $fileManager

# Ativar Floating
bind = $mainMod SHIFT, SPACE, togglefloating,

# Rofi
bind = $mainMod, D, exec, $menu

# Modos
#bind = $mainMod, P, pseudo, # dwindle
bind = $mainMod SHIFT, B, togglesplit, # dwindle

# Mover foco com vim keys
bind = $mainMod, h, movefocus, l
bind = $mainMod, l, movefocus, r
bind = $mainMod, k, movefocus, u
bind = $mainMod, j, movefocus, d

# Mover janelas com vim keys
bind = $mainMod SHIFT, h, movewindow, l
bind = $mainMod SHIFT, l, movewindow, r
bind = $mainMod SHIFT, k, movewindow, u
bind = $mainMod SHIFT, j, movewindow, d

# Mover entre workspaces
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8
bind = $mainMod, 9, workspace, 9
bind = $mainMod, 0, workspace, 10

# Mover janelas entre workspaces
bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5
bind = $mainMod SHIFT, 6, movetoworkspace, 6
bind = $mainMod SHIFT, 7, movetoworkspace, 7
bind = $mainMod SHIFT, 8, movetoworkspace, 8
bind = $mainMod SHIFT, 9, movetoworkspace, 9
bind = $mainMod SHIFT, 0, movetoworkspace, 10

# Mover entre workspaces com scroll
bind = $mainMod, mouse_down, workspace, e+1
bind = $mainMod, mouse_up, workspace, e-1

# Resize de janelas com mouse
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow

# Laptop multimedia keys for volume and LCD brightness
bindel = ,XF86AudioRaiseVolume, exec, wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+
bindel = ,XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bindel = ,XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
bindel = ,XF86AudioMicMute, exec, wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle
bindel = ,XF86MonBrightnessUp, exec, brightnessctl s 10%+
bindel = ,XF86MonBrightnessDown, exec, brightnessctl s 10%-

# Requires playerctl
bindl = , XF86AudioNext, exec, playerctl next
bindl = , XF86AudioPause, exec, playerctl play-pause
bindl = , XF86AudioPlay, exec, playerctl play-pause
bindl = , XF86AudioPrev, exec, playerctl previous

# Cmus
bind = SHIFT, XF86AudioMute, exec, alacritty --working-directory ~/Músicas -e ~/bin/cmusWal
bind = SHIFT, XF86AudioRaiseVolume, exec, cmus-remote -v +5%
bind = SHIFT, XF86AudioLowerVolume, exec, cmus-remote -v -5%

# Run Pywaltic
bind = SUPER_SHIFT, R, exec, ~/bin/pywaltic

# Run setWal
bind = SUPER_SHIFT, S, exec, ~/bin/setWal

# Run navegadores
bind = SUPER_SHIFT, N, exec, ~/bin/navegadores

# Run downloadmp3
bind = SUPER_SHIFT, Y, exec, ~/bin/downloadmp3

# Fullscreen
bind = SUPER, F, fullscreen

# Flameshot
bind = SUPER_SHIFT, P, exec, flameshot gui

# Run logout
bind = SUPER_SHIFT, X, exec, ~/bin/logout

# Run diaNoite
bind = SUPER_SHIFT, F12, exec, ~/bin/diaNoite

# Run pavucontrol
bind = SUPER_SHIFT, V, exec, pavucontrol

# Mod+Shift+< (esquerda)
bind = SUPER_SHIFT, comma, exec, ~/.config/hypr/scripts/move-ws.sh left

# Mod+Shift+> (direita)
bind = SUPER_SHIFT, period, exec, ~/.config/hypr/scripts/move-ws.sh right
